name: bash

on:
  workflow_dispatch:
  schedule:
    - cron: '11 1 * * 1'

permissions:
  contents: write
  id-token: write

concurrency:
  group: "bash"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          bash bash.sh

          git config user.name $(git log -1 --pretty=format:'%an')
          git config user.email $(git log -1 --pretty=format:'%ae')
          git add .
          git diff-index --quiet HEAD || git commit -m "update"
          git push
