name: tmux

on:
  workflow_dispatch:
  schedule:
    - cron: "33 3 * * 3"

permissions:
  contents: write
  id-token: write

concurrency:
  group: "tmux"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          #docker run --rm -v $(pwd):/mnt -w /mnt alpine sh tmux.sh
          docker run --rm -v $(pwd):/mnt -w /mnt debian:bookworm-slim bash tmux.sh

          git config user.name $(git log -1 --pretty=format:"%an")
          git config user.email $(git log -1 --pretty=format:"%ae")
          git add .
          git diff-index --quiet HEAD || git commit -m "update"
          git push
